In [1]:
import numpy as np

print("1. Create a numpy array of size 2 x 2")
# Method 1: Using np.array()
array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 array:")
print(array_2x2)
print(f"Shape: {array_2x2.shape}\n")

print("2. Create a random numpy array of size 3 x 4")
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 array:")
print(random_3x4)
print(f"Shape: {random_3x4.shape}\n")

print("3. Create a numpy array of ones and a numpy array of zeroes")
# Ones array
ones_array = np.ones((3, 3))
print("Ones array (3x3):")
print(ones_array)

# Zeros array
zeros_array = np.zeros((2, 4))
print("Zeros array (2x4):")
print(zeros_array)
print()

print("4. Create a random numpy array of size 6x3 and transpose it")
random_6x3 = np.random.rand(6, 3)
print("Original 6x3 array:")
print(random_6x3)
print(f"Original shape: {random_6x3.shape}")

transposed_array = random_6x3.T
print("Transposed array (3x6):")
print(transposed_array)
print(f"Transposed shape: {transposed_array.shape}\n")

print("5. Create two random numpy arrays and compute dot product")
# Define dimensions
n, p, m = 4, 3, 5

# Create random arrays
array1 = np.random.rand(n, p)  # n x p
array2 = np.random.rand(p, m)  # p x m

print(f"Array 1 ({n}x{p}):")
print(array1)
print(f"Array 2 ({p}x{m}):")
print(array2)

# Compute dot product
dot_product = np.dot(array1, array2)
print(f"Dot product result ({n}x{m}):")
print(dot_product)
print(f"Dot product shape: {dot_product.shape}")

# Alternative method using @ operator
dot_product_alt = array1 @ array2
print("\nUsing @ operator (same result):")
print(dot_product_alt)

1. Create a numpy array of size 2 x 2
2x2 array:
[[1 2]
 [3 4]]
Shape: (2, 2)

2. Create a random numpy array of size 3 x 4
Random 3x4 array:
[[0.08308545 0.91663668 0.52184846 0.52980597]
 [0.56939762 0.29972547 0.57435928 0.75289854]
 [0.27185381 0.73036301 0.80222286 0.37709059]]
Shape: (3, 4)

3. Create a numpy array of ones and a numpy array of zeroes
Ones array (3x3):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zeros array (2x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

4. Create a random numpy array of size 6x3 and transpose it
Original 6x3 array:
[[0.94201624 0.93762494 0.21449715]
 [0.49009753 0.40225944 0.33739808]
 [0.6611032  0.33240924 0.24597327]
 [0.8661748  0.86220984 0.04175162]
 [0.30565572 0.19315143 0.75357952]
 [0.81162894 0.14841649 0.88283793]]
Original shape: (6, 3)
Transposed array (3x6):
[[0.94201624 0.49009753 0.6611032  0.8661748  0.30565572 0.81162894]
 [0.93762494 0.40225944 0.33240924 0.86220984 0.19315143 0.14841649]
 [0.21449715 0.33739808 0.24597327 0.04175162 0.75357